version: '3.8'
services:
  nextjs-app:
    build:
      context: ./yt-controller
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  socket-api:
    build:
      context: ./yt-controller-ytdlp-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge